name: GitHub Release Bot
description: Telegram bot for tracking GitHub releases
services:
  - name: github-release-bot
    image: github-release-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN={{ BOT_TOKEN }}
      - GITHUB_TOKEN={{ GITHUB_TOKEN }}
      - CHANNEL_ID={{ CHANNEL_ID }}
      - ADMIN_ID={{ ADMIN_ID }}
      - CHECK_INTERVAL_MINUTES={{ CHECK_INTERVAL_MINUTES | default("60") }}
    volumes:
      - bot_data:/app/data
    restart_policy: unless-stopped
    health_check:
      test: ["CMD-SHELL", "python -c 'import sys; sys.exit(0)'"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    resource_limits:
      memory_megabytes: 768
      cpu_cores: 0.75
    labels:
      coolify.managed: "true"
      coolify.type: "application"
