version: '3.9'

services:
  github-release-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: github-release-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - ADMIN_ID=${ADMIN_ID}
      - CHECK_INTERVAL_MINUTES=${CHECK_INTERVAL_MINUTES:-60}
    volumes:
      - bot_data:/app/data
      - ./.env:/app/.env:ro
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: '0.75'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import sys; sys.exit(0)'"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    networks:
      - bot-network
    labels:
      - "coolify.managed=true"
      - "coolify.type=application"

volumes:
  bot_data:
    driver: local

networks:
  bot-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
