version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-release-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - ADMIN_ID=${ADMIN_ID}
      - CHECK_INTERVAL_MINUTES=${CHECK_INTERVAL_MINUTES:-60}
    volumes:
      - data:/app/data
    networks:
      - app-network

volumes:
  data:

networks:
  app-network:
    driver: bridge
