version: '3.8'

services:
  github-release-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: github-release-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - ADMIN_ID=${ADMIN_ID}
      - CHECK_INTERVAL_MINUTES=${CHECK_INTERVAL_MINUTES:-60}
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
    deploy:
      resources:
        limits:
          memory: 1.5G  # Ограничиваем память
          cpus: '1.5'    # Ограничиваем CPU
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
